### PR TITLE
Replace offending characters (non-alphanumeric,_ or -) with -

### PR DESCRIPTION
**Pull request by akramhussein**
Created character set to represent all offending characters and replace with default of `-`.

### CODE REVIEW

**Comment by akramhussein** [comment]
You may wish to refactor - I'm a little rusty with Objective-C and can't remember best practice for encapsulation of properties.

**Comment by ladanazita** [comment]
@f2prateek 👀

**Comment by f2prateek** [comment]
LGTM! I think we can make it simpler by using [`stringByReplacingCharactersInRange `](https://developer.apple.com/library/ios/documentation/Cocoa/Reference/Foundation/Classes/NSString_Class/index.html#//apple_ref/occ/instm/NSString/stringByReplacingCharactersInRange:withString:). The range would be non-alphanumeric characters, `-` and `_`.

**Comment by akramhussein** [comment]
Hi @f2prateek, thank you for taking a look.

I'm not sure I follow. The method `stringByReplacingCharactersInRange`, says `Returns a new string in which the characters in a specified range of the receiver are replaced by a given string.` 

My understanding is the range would be a portion of the un-sanitised event name and not characters we want to use. Is this not correct? Not sure how I'd implement this.

**Comment by f2prateek** [comment]
Ah correct, I meant the range would would be non-alphanumeric characters and anything *NOT* `-` or `.`.

**Pull request closed without merging**
